src/AppBundle/Entity/Network.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="network",indexes={@ORM\Index(name="network_code", columns={"NetworkCode"})},
 * uniqueConstraints={@ORM\UniqueConstraint(name="UniqueNetwrok", columns={"Name", "NetworkCode"})})
 * @ORM\Entity(repositoryClass="AppBundle\Entity\NetworkRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Network {

    /**
     * @ORM\Column(type="guid",name="Code")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $code;

    /**
     * @ORM\Column(type="string",name="Name")
     */
    private $name;

    /**
     * @ORM\Column(type="string", name="NetworkCode")
     */
    private $networkCode;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="User", referencedColumnName="Code")
     */
    private $user;

    /**
     * @ORM\Column(type="string", name="Email", nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", name="Phone", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", name="UserName", nullable=true)
     */
    private $userName;

    /**
     * @ORM\Column(type="boolean", name="UserNameVerified", nullable=true)
     */
    private $userNameVerified;

    /**
     * @ORM\Column(type="datetime", name="Date")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean", name="Visible")
     */
    private $visible;

    /**
     * @ORM\Column(type="string", name="Token", nullable=true)
     */
    private $token;

    public function getCode() {
        return $this->code;
    }

    public function setCode($code) {
        $this->code = $code;
    }

    public function getName() {
        return $this->name;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function getUser() {
        return $this->user;
    }

    public function setUser($user) {
        $this->user = $user;
    }

    public function getEmail() {
        return $this->email;
    }

    public function setEmail($email) {
        $this->email = $email;
    }

    public function getPhone() {
        return $this->phone;
    }

    public function setPhone($phone) {
        $this->phone = $phone;
    }

    public function getNetworkCode() {
        return $this->networkCode;
    }

    public function setNetworkCode($networkCode) {
        $this->networkCode = $networkCode;
    }

    public function getDate() {
        return $this->date;
    }

    public function setDate($date) {
        $this->date = $date;
    }

    public function getVisible() {
        return $this->visible;
    }

    public function setVisible($visible) {
        $this->visible = $visible;
    }

    public function getToken() {
        return $this->token;
    }

    public function setToken($token) {
        $this->token = $token;
    }

    public function getUserName() {
        return $this->userName;
    }

    public function setUserName($userName) {
        $this->userName = $userName;
    }

    public function getUserNameVerified() {
        return $this->userNameVerified;
    }

    public function setUserNameVerified($userNameVerified) {
        $this->userNameVerified = $userNameVerified;
    }

    public function getDisplayName() {
        if ($this->name === "fb") {
            return "Facebook.com";
        }
        if ($this->name === "g") {
            return "Google.com";
        }
        if ($this->name === "tw") {
            return "Twitter.com";
        }
    }

    public function getDisplayUrl() {
        if ($this->name === "fb") {
            return "https://www.facebook.com";
        }
        if ($this->name === "g") {
            return "https://plus.google.com";
        }
        if ($this->name === "tw") {
            return "https://www.twitter.com";
        }
    }

    /**
     * @ORM\PrePersist
     */
    public function beforePersist() {
        $this->date = new \DateTime();
    }

}

src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Table(name="user",indexes={@ORM\Index(name="Email", columns={"email"}),@ORM\Index(name="Phone", columns={"phone"})})
 * @ORM\Entity(repositoryClass="AppBundle\Entity\UserRepository")
 * @ORM\HasLifecycleCallbacks
 */
class User {

    /**
     * @ORM\Column(type="guid", name="Code")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $code;

    /**
     * @ORM\Column(type="string", name="Email",nullable=true, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", name="Name", nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", name="Phone", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean", name="Active")
     */
    private $active;

    /**
     * @ORM\Column(type="string", name="Seckey", nullable=true)
     */
    private $seckey;

    /**
     * @ORM\Column(type="guid", name="Verification", nullable=true)
     */
    private $verification;

    /**
     * @ORM\Column(type="datetime", name="Date")
     */
    private $date;

    public function getCode() {
        return $this->code;
    }

    public function getName() {
        return $this->name;
    }

    public function getPhone() {
        return $this->phone;
    }

    public function getEmail() {
        return $this->email;
    }

    public function getActive() {
        return $this->active;
    }

    public function getSecKey() {
        return $this->seckey;
    }

    public function getVerification() {
        return $this->verification;
    }

    public function getDate() {
        return $this->date;
    }

    public function setCode($code) {
        $this->name = $code;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function setPhone($phone) {
        $this->phone = $phone;
    }

    public function setEmail($email) {
        $this->email = $email;
    }

    public function setActive($active) {
        $this->active = $active;
    }

    public function setSecKey($seckey) {
        $this->seckey = $seckey;
    }

    public function setVerification($verification) {
        $this->verification = $verification;
    }

    public function setDate($date) {
        $this->date = $date;
    }

    /**
     * @ORM\PrePersist
     */
    public function beforePersist() {
        $this->date = new \DateTime();
    }

    public function getDisplayName() {
        if ($this->name)
            return $this->name;
        else if ($this->email)
            return $this->email;
        else if ($this->phone)
            return $this->phone;
    }
        public function getOneIdentifier() {
        if ($this->email)
            return $this->email;
        else if ($this->phone)
            return $this->phone;
        else if ($this->code)
            return $this->code;
    }

}

src/AppBundle/Controller/UserController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use AppBundle\Entity\User;
use AppBundle\Entity\UserInfo;
use AppBundle\Entity\Network;
use Abraham\TwitterOAuth\TwitterOAuth;
use Abraham\TwitterOAuth\TwitterOAuthException;

class UserController extends Controller {

    //This action only old school own register  (no social network, or login kit)
    public function registerAction(Request $request) {
        $responseArray = array();
        $response = new Response();
        $userJSON = $request->request->get('user');
        if ($userJSON === null) {
            $response->setStatusCode(400);
            $response->setContent('{"error": null post data "}');
            return $response;
        }
        $userArray = json_decode($userJSON, true);
        if (isset($userArray['email'])) {
            $email = $userArray['email'];
        } else {
            $email = null;
        }
        if (isset($userArray['phone'])) {
            $phone = $userArray['phone'];
        } else {
            $phone = null;
        }
        if (isset($userArray['name'])) {
            $name = $userArray['name'];
        } else {
            $name = null;
        }

        $em = $this->getDoctrine()->getManager();
        $userInfo = $this->getDoctrine()->getRepository('AppBundle:UserInfo')->findOneBy(array("type" => "email", "info" => $email));

        if ($userInfo) {
            $user = $userInfo->getUser();
            $user->setVerification(uniqid("", true));
            $em->persist($user);
            $em->flush();
        } else {
            $user = new User();
            $user->setEmail($email);
            $user->setPhone($phone);
            $user->setName($name);
            $user->setActive(false);
            $user->setVerification(uniqid("", true));
            $em->persist($user);
            $em->flush();
            $userInfo = new UserInfo();
            $userInfo->setType("email");
            $userInfo->setInfo($email);
            $userInfo->setUser($user);
            $userInfo->setactive(false);
            $userInfo->setvisible(true);
            $em->persist($userInfo);
            $em->flush();
        }
        if ($user->getEmail()) {
            $mailer = $this->get('app.mailer');
            $template = $this->renderView("emails/activate-user.html.twig", array('user' => $user));
            $mailer->sendEmail("Activar usuario", $user->getEmail(), $template);
            $responseArray["success"] = "Un correo ha sido enviado para activar el usuario.";
        }


        $response->setContent(json_encode($responseArray));
        return $response;
    }

    public function activateUserAction(Request $request, $code) {
        $session = $request->getSession();
        $errorSocialLogin = $session->getFlashBag()->get('errorSocialLogin');


        $renderArray = Array();
        if ($errorSocialLogin)
            $renderArray["errorSocialLogin"] = $errorSocialLogin[0];

        $renderArray['userSession'] = null;

        if (strpos($code, '&')) {
            $keywords = preg_split("/[&]/", $code);
            $code = $keywords[0];
            $verification = $keywords[1];
            $email = $keywords[2];
        }

        $em = $this->getDoctrine()->getManager();
        $user = $this->getDoctrine()->getRepository('AppBundle:User')->find($code);
        if ($user === null) {
            return $this->render('AppBundle:user:activate-error.html.twig', $renderArray);
        }

        if ($user->getActive() === false) {
            $session->set("userSession", null);
            $renderArray['user'] = $user;
            return $this->render('AppBundle:user:create-key.html.twig', $renderArray);
        } else {
            $session->set("userSession", $user);
            return $this->redirectToRoute('home', array('userSession' => $user));
        }
    }

    public function loginAction(Request $request) {
        $responseArray = array();
        $response = new Response();
        $userJson = $request->request->get('user');
        if ($userJson === null) {
            $response->setStatusCode(400);
            $response->setContent('{"error": null post data "}');
            return $response;
        }
        $userArray = json_decode($userJson, true);
        $email = $userArray['email'];
        $seckey = $userArray['seckey'];

        $em = $this->getDoctrine()->getManager();
        $userInfo = $this->getDoctrine()->getRepository('AppBundle:UserInfo')->findOneBy(array("type" => "email", "info" => $email));
        if ($userInfo) {

            $user = $userInfo->getUser();
            if ($user->getSecKey() === $seckey) {
                $responseArray['success'] = "indentified";
                $session = $request->getSession();
                $session->set("userSession", $user);
            } else {
                $response->setStatusCode(300);
                $responseArray["error"] = "Identificación incorrecta!";
            }
        } else {
            $response->setStatusCode(300);
            $responseArray["error"] = "Identificación incorrecta!";
        }
        $response->setContent(json_encode($responseArray));
        return $response;
    }

    public function logoutAction(Request $request) {
        $url = $request->headers->get('referer');
        $session = $request->getSession();
        $session->remove("userSession");
        return $this->redirect($url);
    }

    public function createSecKeyAction(Request $request) {
        $response = new Response();
        $userJson = $request->request->get('user');
        if ($userJson === null) {
            $response->setStatusCode(400);
            $response->setContent('{"error": null post data "}');
            return $response;
        }
        $userArray = json_decode($userJson, true);
        $userCode = $userArray['code'];
        $seckey = $userArray['seckey'];

        $em = $this->getDoctrine()->getManager();
        $user = $this->getDoctrine()->getRepository('AppBundle:User')->find($userCode);

        $user->setSecKey($seckey);
        $user->setActive(true);
        $em->persist($user);
        $userInfo = $this->getDoctrine()->getRepository('AppBundle:UserInfo')->findOneBy(array("type" => "email", "info" => $user->getEmail()));
        $userInfo->setActive(true);
        $em->persist($userInfo);
        $em->flush();

        $session = $request->getSession();
        $session->set("userSession", $user);

        $response->setContent('{"success":"El usuario ahora tiene contraseña."}');
        return $response;
    }

    public function validateUserAction(Request $request) {
        $response = new Response();
        $userJson = $request->request->get('user');

        if ($userJson === null) {
            $response->setStatusCode(400); //bad request
            $response->setContent('{"error":  post data es nulo "}');

            return $response;
        }
        $userArray = json_decode($userJson, true);
        $email = $userArray['email'];
        $userInfo = $this->getDoctrine()->getRepository('AppBundle:UserInfo')->findOneBy(array("type" => "email", "info" => $email));

        if ($userInfo) {
            $user = $userInfo->getUser();
            if ($user->getSecKey() !== null && $user->getSecKey() !== "") {
                $response->setContent('{"success":"Usuario existe y tiene llave."}');
            } else {

                $response->setStatusCode(300);
                $response->setContent('{"error":"El usuario no tiene contraseña."}');
            }
        } else {
            $response->setStatusCode(300);
            $response->setContent('{"error":"El usuario no existe."}');
        }

        return $response;
    }

    public function recoveryKeyAction(Request $request) {
        $session = $request->getSession();
        $userSession = $session->get("userSession");

        return $this->render('AppBundle:user:recovery-key.html.twig', array("userSession" => $userSession));
    }

    public function notifyNewKeyAction(Request $request) {

        $response = new Response();
        $userJson = $request->request->get('user');
        if ($userJson === null) {
            $response->setStatusCode(400);
            $response->setContent('{"error": "null post data "}');
            return $response;
        }

        $captcha = $request->request->get('captcha');
        if ($captcha === null) {
            $response->setStatusCode(400);
            $response->setContent('{"error": "null post captcha "}');
            return $response;
        }

        $reCaptcha = $this->get('app.captcha');
        $captchaData = $reCaptcha->validateCaptcha($captcha);
        $captchaJson = json_decode($captchaData, true);
        if ($captchaJson['success'] === false) {
            $response->setStatusCode(300);
            $response->setContent('{"error": "Error en el captcha."}');
            return $response;
        }

        $userArray = json_decode($userJson, true);
        $userEmail = $userArray['email'];

        $userInfo = $this->getDoctrine()->getRepository('AppBundle:UserInfo')->findOneBy(array("type" => "email", "info" => $userEmail));

        if ($userInfo === null) {
            $response->setStatusCode(300);
            $response->setContent('{"error": "El correo no existe, crea una nueva moneda para continuar."}');
            return $response;
        }
        $user = $userInfo->getUser();

        $em = $this->getDoctrine()->getManager();
        $user->setVerification(uniqid("", true));
        $em->persist($user); // to change the verification code
        $em->flush();

        $mailer = $this->get('app.mailer');
        $template = $this->renderView("emails/user-new-key.html.twig", array('user' => $user));

src/AppBundle/Resources/views/user/activate-error.html.twig
{% extends "AppBundle::base.html.twig" %}


{% block body %}
    <h2>Error!</h2>
    <h3>Revisa el link! </h3>
{%endblock%}

src/AppBundle/Resources/views/user/create-key.html.twig
{% extends "AppBundle::base.html.twig" %}
{%block css %}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/appbundle/css/user/activate-missing-key.css') }}" >
{%endblock%}

{%block body %}
    <input type="hidden" id="userCode" value="{{user.code}}" />
    {{ include ('AppBundle:index:menu.html.twig') }}

    <h3 class="text-primary">Iniciar sesión</h3>
    <input type="hidden" id="verification" value="{{user.verification}}"></input>
    <div  class="alert alert-info">Nueva contraseña para <label id="userEmail"><b> {{user.email}}</b> </label></div>
    {%if errorSocialLogin is defined %}
        <div style="font-size: 1.1rem; display: inline-block; width: 100%" class="alert alert-danger" >{{errorSocialLogin}}</div>
    {%endif%}

    <div class="card ">
        <div class="card-header">
            <label>El usuario  necesita una sesión. Crea una contraseña o inicia con una red social.</label>
            <label class="lead">Esto te permitirá liberar, transferir, reclamar, crear y recibir otras monedas.</label>
        </div>
        <div class="card-block">


            <div class="old-school-login">
                <div class = "div-password">
                    <label class="control-label text-primary" ><b>Contraseña: </b></label>
                    <div>
                        <input id="seckey1" class="form-control" type="password" autofocus=""></input>
                    </div>
                </div>
                </br>

                <div class="div-password" >
                    <label class="control-label text-primary"><b>Reescriba la contraseña: </b></label>
                    <div>
                        <input id="seckey2" class="form-control " type="password"></input>
                    </div>
                </div>

                <span class="alert alert-danger"></span>
                <span class="alert alert-success"></span>

                <div><button type="button" class="btn btn-primary btn-lg btn-login">Iniciar sesión</button><img id="processing-image" src="{{asset('bundles/appbundle/img/loading-login.gif')}}"></div>
            </div>

            <div class="social-network-login ">
                <div style="display: block"><label class="text-primary">Redes sociales:</label></div>
                <div class="fblogin">
                    <button class="btn btn-primary btn-lg btn-fb-login">Facebook</button>

                </div>
                <div class="twlogin">
                    <button class="btn btn-primary btn-lg btn-tw-login">Twitter</button>

                </div>
                <div class="glogin">
                    <button class="btn btn-primary btn-lg btn-g-login" disabled="true">Google</button>

                </div>
                <img id="login-processing-image" src="{{asset('bundles/appbundle/img/loading-login.gif')}}">

                <div><span class="login alert alert-danger"></span></div>
            </div>


        </div>
    </div>
{%endblock %}

{%block js %}
    <script>
        var changeKeyUrl = "{{ path('createSecKey') }}";
        var fbLoginUrl = "{{path('fbLogin')}}";
        var gLoginUrl = "{{path('gLogin')}}";
    </script>

    <script src="{{ asset('bundles/appbundle/js/user/new-key.js')}}"></script>

    <script src="{{ asset('bundles/appbundle/js/md5.js')}}"></script>
{%endblock%}

src/AppBundle/Resources/views/user/new-key-error.html.twig
{% extends "AppBundle::base.html.twig" %}
{%block body %}
        <h2>Error!</h2>
        <h3>Revisa el link! </h3>
{%endblock%}

src/AppBundle/Resources/views/user/new-key.html.twig
{% extends "AppBundle::base.html.twig" %}
{%block css %}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/appbundle/css/user/activate-missing-key.css') }}" >
{%endblock%}

{%block body %}
    <input type="hidden" id="userCode" value="{{user.code}}" />
    {{ include ('AppBundle:index:menu.html.twig') }}

    <h3 class="text-primary">Iniciar sesión</h3>
    <input type="hidden" id="verification" value="{{user.verification}}"></input>
    <div class="alert alert-info">Nueva contraseña para <label id="userEmail"> {{user.email}} </label></div>

    {%if errorSocialLogin is defined %}
        <div style="font-size: 1.1rem; display: inline-block; width: 100%" class="alert alert-danger" >{{errorSocialLogin}}</div>
    {%endif%}
    
    <div class="card ">
        <div class="card-header">
            <label>Cambia tu contraseña o inicia con una red social.</label>
            <label class="lead">Esto te permitirá liberar, transferir, reclamar, crear y recibir otras monedas.</label>
        </div>
        <div class="card-block">


            <div class="old-school-login">
                <div class = "div-password">
                    <label class="control-label text-primary" ><b>Contraseña: </b></label>
                    <div>
                        <input id="seckey1" class="form-control" type="password" autofocus=""></input>
                    </div>
                </div>
                </br>

                <div class="div-password" >
                    <label class="control-label text-primary"><b>Reescriba la contraseña: </b></label>
                    <div>
                        <input id="seckey2" class="form-control " type="password"></input>
                    </div>
                </div>

                <span class="alert alert-danger"></span>
                <span class="lead alert alert-success"></span>

                <div><button type="button" class="btn btn-primary btn-lg btn-login">Iniciar sesión</button><img id="processing-image" src="{{asset('bundles/appbundle/img/loading-login.gif')}}"></div>
            </div>

            <div class="social-network-login ">
                <div style="display: block"><label class="text-primary">Redes sociales:</label></div>
                <div class="fblogin">
                    <button class="btn btn-primary btn-lg btn-fb-login">Facebook</button>

                </div>
                <div class="twlogin">
                    <button class="btn btn-primary btn-lg btn-tw-login">Twitter</button>

                </div>
                <div class="glogin">
                    <button class="btn btn-primary btn-lg btn-g-login" disabled="true">Google</button>

                </div>
                <img id="login-processing-image" src="{{asset('bundles/appbundle/img/loading-login.gif')}}">
                <div><span class="login alert alert-danger"></span></div>
            </div>


        </div>
    </div>
{%endblock %}

{%block js %}
    <script>
        var changeKeyUrl = "{{ path('changeKey') }}";
        var fbLoginUrl = "{{path('fbLogin')}}";
        var gLoginUrl = "{{path('gLogin')}}";
    </script>

    <script src="{{ asset('bundles/appbundle/js/user/new-key.js')}}"></script>

    <script src="{{ asset('bundles/appbundle/js/md5.js')}}"></script>
{%endblock%}

src/AppBundle/Resources/views/user/social-info.html.twig
<table id="tableSocialInfo" class="table table-striped">
    <thead>
        <tr>

            <th>
                <label>
                    Red social
                </label>
            </th>

        </tr>
    </thead>
    <tbody>
        {% set twitter=false %}
        {%set google=false %}
        {%set facebook=false %}
        {%for userNetwork in userNetworks%}
            {%if userNetwork.name=="tw"%}
                {% set twitter=true %}
            {%endif%}
            {%if userNetwork.name=="g"%}
                {% set google=true %}
            {%endif%}
            {%if userNetwork.name=="fb"%}
                {% set facebook=true %}
            {%endif%}
            <tr>



                {%if userNetwork.userName and userNetwork.userNameVerified %}
                    <td>           
                        <div class="social-network">
                            <input class="network-code" type="hidden"  value="{{userNetwork.code}}"/>
                            {%if ("https://" in userNetwork.userName) or ("http://" in userNetwork.userName) %}
                                <a class="link-social" href="{{userNetwork.userName}}"> {{userNetwork.userName}}</a>

                            {%else%}
                                <a class="link-social" href="{{userNetwork.displayUrl}}/{{userNetwork.userName}}"> {{userNetwork.displayUrl}}/{{userNetwork.userName}}</a>
                            {%endif%}
                            <div class='checkbox checkbox-slider-lg checkbox-slider--b  checkbox-slider-info '>
                                <label>
                                    <input class="inputUserNetwork" type='checkbox' {%if userNetwork.visible %} org_checked=true checked='checked' {%endif%}><span></span>
                                </label>
                            </div>
                            <div class="btn-actions">
                                <button type="button" class="btn btn-secondary btn-trash-social" {%if not userNetwork.userName %} style="display:none" {%endif%}>
                                    <span class="fa fa-trash-o fa-lg "></span>
                                </button>
                                <button type="button" class="btn btn-secondary btn-refresh-social">
                                    <span class="fa fa-refresh fa-lg"></span>
                                </button>
                            </div>

                        </div>

                    </td>
                {%else%}
                    <td class="table-danger">
                        <label id="label-ask-fb-username" {%if userNetwork.username %}style="display:none"{%endif%}>Facebook no comparte esta información. Agregala tu.</label>

                        <label id="label-confirm-fb" {%if not userNetwork.username %}style="display:none"{%endif%}>Verfica esta información enviando un mensaje a este <a target="_blank" href="{{fb_client_page}}">perfil</a> en fb.</label>

                        <div class="div-edit-network-user" >
                            <input class="last-fb-username" type="hidden"  value="{{userNetwork.username}}"/>
                            <input class="network-code" type="hidden"  value="{{userNetwork.code}}"/>

                            <label id="label-network-url">https://www.{{userNetwork.displayName|lower}}/</label>
                            <input type="hidden" class="form-control" {%if userNetwork.userName%} value="{{userNetwork.userName}}" {%else%} value="" {%endif%}   />
                            <input id="fb-given-username" class="form-control" {%if userNetwork.userName%} readonly="" value="{{userNetwork.userName}}"{%else%} value=""{%endif%}   autofocus=""  />

                            <div class='checkbox checkbox-slider-lg checkbox-slider--b  checkbox-slider-info '>
                                <label>
                                    <input class="inputUserNetwork" type='checkbox' {%if userNetwork.visible %} org_checked=true checked='checked' {%endif%}><span></span>
                                </label>
                            </div>

                            <div class="btn-actions">
                                <button type="button" class="btn btn-secondary btn-edit-social" {%if not userNetwork.userName %} style="display:none" {%endif%} >
                                    <span class="fa fa-pencil-square-o fa-lg" aria-hidden="true" ></span>
                                </button>

                                <button type="button" class="btn btn-secondary btn-ok-social" {%if userNetwork.userName %} style="display:none" {%endif%} >
                                    <span class="fa fa-check" ></span>
                                </button>
                                <button type="button" class="btn btn-secondary btn-cancel-social" {%if userNetwork.userName %} style="display:none" {%endif%} >
                                    <span class="fa fa-times" ></span>
                                </button>
                                <button type="button" class="btn btn-secondary btn-trash-social" {%if not userNetwork.userName %} style="display:none" {%endif%}>
                                    <span class="fa fa-trash-o fa-lg"></span>
                                </button>
                                <button type="button" class="btn btn-secondary btn-refresh-social">
                                    <span class="fa fa-refresh fa-lg"></span>
                                </button>
                            </div>


                        </div>
                    </td>
                {%endif%}








            </tr>

        {%endfor%}
        <tr>
            <td>

                <span class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-plus fa-lg" aria-hidden="true"></span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {%if not twitter %}
                            <a id="link-tw-login" class="dropdown-item" href="#">Twitter</a>
                        {%endif%}
                        {%if not google %}
                            <a id="link-g-login" class="dropdown-item" href="#" disabled="">Google+</a>
                        {%endif%} 
                        {%if not facebook%}
                            <a id="link-fb-login" class="dropdown-item" href="#">Facebook</a>
                        {%endif%}
                    </div>
                </span>
                <img id="adding-processing-image" src="{{asset('bundles/appbundle/img/loading-login.gif')}}">

            </td>

        </tr>
    </tbody>
</table>
<span class="alert alert-danger alert-add-social"></span>
<span class="alert alert-success success-add-social"></span>